import PreviousSearches from "../components/PreviousSearches";
import RecipeCard from "../components/RecipeCard";

export default function Recipes() {
  const recipes = [
    {
      title: "White Sauce Pasta",
      image: "/images/recipes/11.jpg",
      authorImg: "/images/topchefs/img_1.jpg",
      desc: "White Sauce Pasta is simply cooked pasta mixed with a silky smooth & decadent white sauce made of milk, butter and flour.",
      authorName: "Fivel Stewart",
      ingredients: ["1 (16-ounce) package (about 4 cups) penne", <br />, "3 tablespoons unsalted butter", <br />, "2 teaspoons minced garlic", <br />, "3 tablespoons all-purpose flour", <br />, "1 cup milk", <br />, "1 cup chicken broth", <br />, "1 cup grated Parmesan cheese", <br />, "2 teaspoons dried parsley,garlic salt with parsley flakes or salt to taste,pepper to taste", <br />, "½ cup shredded mozzarella cheese or additional Parmesan cheese optional."],

      directions: ["1.Cook pasta according to package directions. Drain and set aside.", <br />, "2.Meanwhile, in a large saucepan, melt butter over medium heat. Add garlic and cook, stirring, for 1 minute.", <br />, "3.Add flour and cook, stirring constantly, for 1 minute more.", <br />, "4.Add milk and broth and cook, stirring constantly, until the sauce boils and thickens, about 5 minutes.", <br />, "5.Add Parmesan, parsley, garlic salt and pepper. Continue stirring until the cheese has melted.", <br />, "6.Add pasta to the sauce and stir to combine. Add mozzarella and stir until melted. Serve warm."],

      preptime: "5 minutes",
      cooktime: "10 minutes",
      totaltime: "15 minutes",
      servings: "6",
      calories: "191 kcal",
    },
    {
      title: "Spaghetti and Meatballs",
      image: "/images/recipes/12.jpg",
      authorImg: "/images/topchefs/img_2.jpg",
      desc: "Spaghetti and meatballs is an Italian-American dish consisting of spaghetti, tomato sauce and meatballs.",
      authorName: "Patrick Bateman",
      ingredients: [<u>MEATBALLS:</u>, <br />, "500 g/1lb chicken mince (ground chicken), or turkey or pork (Note 1)", <br />, "1/4 small white onion , grated into the bowl", <br />, "1/2 cup panko breadcrumbs", <br />, "1/3 cup grated parmesan", <br />, "1 large garlic clove , minced", <br />, "1/4 cup finely chopped parsley (or 2 tsp dried parsley or basil)", <br />, "1 egg", <br />, "1/4 tsp salt", <br />, "1/2 tsp pepper", <br />, "Olive oil spray (or olive oil)", <br />, <u>PASTA SAUCE:</u>, <br />, "1 tbsp olive oil", <br />, "1 garlic clove , finely chopped", <br />, "3/4 small onion , finely chopped", <br />, "800 g / 28 oz crushed tomato", <br />, "1 cup / 250 ml water (swirl in tomato can to clean out)", <br />, "Handful basil leaves , torn, or 1 tsp dried herbs (e.g. Italian mix, oregano, thyme, basil)", <br />, <u>SERVING:</u>, <br />, "250 g/ 1/2 lb spaghetti or other long strand pasta of choice , cooked per packet", <br />, "Fresh basil , optional", <br />, "Parmesan cheese"],
      directions: ["1.Preheat oven to 200C/390F (standard) or 180C/350F (fan/convection).", <br />, "2.Place a rack on a tray, and spray the rack with oil.", <br />, "3.Place Meatball ingredients in a bowl, mix well. Scoop up a heaped tablespoon, roll into a ball and place on the rack.", <br />, "4.Repeat with remaining mixture - should make 25 - 30. Tip: spray hands with oil or wet lightly with water.", <br />, "5.Spray each ball well with oil, then bake for 25 minutes until golden brown. Give 'em a squeeze and you'll see how soft they are!", <br />, <u>SAUCE:</u>, <br />, "1.Heat oil in a large skillet over medium high heat. Add garlic and onion, cook for 2 - 3 minutes until translucent. Add tomato and water, stir then turn heat down to medium. Simmer for 5 - 10 minutes, then season to taste with salt and pepper and stir through basil (or use dried herbs).", <br />, <u>SERVING:</u>, <br />, "1.Cook pasta in a large pot of boiling water. Drain then return pasta to the same pot.", <br />, "2.Add Sauce and meatballs, toss.", <br />, "3.Serve, garnished with fresh basil and parmesan."],
      preptime: "10 minutes",
      cooktime: "50 minutes",
      totaltime: "60 minutes",
      servings: "1 (397g)",
      calories: "537 cal",
    },
    {
      title: "American Cheese Burger",
      image: "/images/recipes/13.jpg",
      authorImg: "/images/topchefs/img_3.jpg",
      desc: "Enjoy a mouth-watering meat-free burger that's full of flavor with BOCA Veggie Burgers. Made with soy protein, garlic, onion and cheddar cheese, e.t.c.",
      authorName: "Mathew Murdock",
      ingredients: ["2 medium carrots - peeled and chopped into small (1cm) chunks", <br />, "2 small potatoes - (weighing about 250g/8oz altogether before peeling), peeled and chopped into small (1cm) chunks", <br />, "75 g (2 ½ oz) green beans - fresh or frozen - I used fresh, cut into small (1cm) pieces", <br />, "115 g (⅔ cup) broccoli - florets only - - cut into small pieces", <br />, "150 g (1 ½ cups) grated mature cheddar cheese", <br />, "3 tbsp double (heavy) cream", <br />, "¼ tsp salt", <br />, "¼ tsp pepper", <br />, "60 g (½ cup) plain (all purpose) flour - - seasoned with a pinch of salt and pepper", <br />, "2 eggs - beaten", <br />, "75 g (1 ½ cups) panko or homemade breadcrumbs", <br />, "¾ tsp paprika", <br />, "3 tbsp olive oil", <br />, <u>SERVING:</u>, <br />, "6 brioche buns - ,sliced and toasted", <br />, "12 large lettuce leaves", <br />, "2 tomatoes - sliced", <br />, "½ red onion - , peeled and sliced", <br />, "3 tbsp mayonnaise", <br />, "4 tbsp tomato ketchup"],
      directions: ["1.Place the carrots and potatoes into a medium sized saucepan and cover with water so the water is a couple of inches above the veg. Place on the hob and bring to the boil. Boil gently for 10 minutes.", <br />, "2.Add in the green beans and broccoli, bring back to the boil and continue to cook for a further 2 minutes.", <br />, "3.Drain out the water using a colander (make sure they're fully dry), then transfer to a bowl.", <br />, "4.Gently crush any potatoes you see using a fork. Don't worry if you don't get all of them.", <br />, "5.Add the cheese, cream, salt and pepper to the veg mixture and stir until combined.", <br />, "6.Cover the bowl and refrigerate for 1 hour (or up to a day) to firm up the mixture.", <br />, "7.Preheat the oven to 220C/425F.", <br />, "8.Place the flour, beaten egg and breadcrumbs into 3 separate shallow bowls. Add the paprika and olive oil to the breadcrumbs and stir together until the breadcrumbs are coated in the oil.", <br />, "9.Remove the mixture from the fridge. Take a good scoop of the veggie mixture (about the size of a large plum) and form into a patty.", <br />, "10.Dip the veggie patty in turn into the flour, egg and finally the breadcrumbs, shaking off any excess as you go. Place on a shallow baking tray. Repeat until you’ve used up all of the mixture - it should make 6 patties.", <br />, "11.Place in the oven to cook for 20 minutes - until the breadcrumbs are golden and cheese is just starting to ooze a tiny bit from the burgers.", <br />, "12.Remove from the oven and serve on toasted buns with lettuce, tomato and red onion. Mix together the ketchup and mayo and drizzle on top before placing the tops of the burger buns on the burgers."],
      preptime: "15 minutes",
      cooktime: "20 minutes",
      totaltime: "35 minutes",
      servings: "6",
      calories: "377 kcal",
    },
    {
      title: "Chocolate soufflé",
      image: "/images/recipes/14.jpg",
      authorImg: "/images/topchefs/img_4.jpg",
      desc: "A dark chocolate ganache, deepened with the addition of unsweetened chocolate, makes a simple base that bakes up into a moist, not dry, soufflé.",
      authorName: "Keira Knightley",
      ingredients: [<u>Soufflé Batter</u>, <br />, "4 Tablespoons (1/4 cup; 60g) unsalted butter, cut into 4 Tablespoon size pieces", <br />, "4 ounce (113g) semi-sweet chocolate bar, coarsely chopped*", <br />, "3 large eggs, separated*", <br />, "1 teaspoon pure vanilla extract", <br />, "1/8 teaspoon salt", <br />, "1/8 teaspoon cream of tartar", <br />, "3 Tablespoons (38g) granulated sugar", <br />, <u>Prepping The Ramekins</u>, <br />, "1 Tablespoon (15g) unsalted butter, extra soft (the softer it is, the easier it is to spread)", <br />, "4 teaspoons (16g) granulated sugar"],
      directions: [<u>1.For the batter:</u>, "Melt the 4 Tablespoons of butter and the chopped chocolate together in a double boiler or in a large heatproof bowl in the microwave. Microwave in 20 second increments, stirring after each until completely melted and combined. Slightly cool for 3-5 minutes.", <br />, "2.Whisk egg yolks, vanilla extract, and salt into chocolate mixture. Set aside.", <br />, "3.In a completely clean residue-free medium glass or metal mixing bowl, using a handheld mixer or stand mixer fitted with a whisk attachment, beat the egg whites and cream of tartar together on high speed until soft peaks form, about 2 minutes. With the mixer running on high speed, slowly add the sugar in 3 additions about 1 Tablespoon at a time, beating for 5 seconds before adding the next Tablespoon. After all 3 Tablespoons of sugar have been added, beat until stiff glossy peaks form, about 2 more minutes. Do not over-beat.", <br />, "4.Slowly and gently fold the egg whites into the chocolate mixture. It’s best to do this in 3 separate additions, combining each addition completely before folding in more.", <br />, "5.Refrigerate the batter for 5-10 minutes as you preheat the oven and prepare the ramekins. (No need to cover the batter unless you are refrigerating it for longer than 1 hour. Can be made up to 2 days in advance, see make ahead instructions below.)", <br />, "6.Adjust the oven rack to the lower third position and preheat to 400°F (204°C).", <br />, <u>7.Prepare the ramekins:</u>, "Brush four 6-ounce oven-safe straight sided ramekins with a generous coating of the softened butter. Sprinkle in the granulated sugar, then shake/rotate each to ensure every spot of the ramekin has a sugar coating. Place ramekins on a baking sheet. Discard excess sugar.", <br />, "8.Spoon batter evenly into ramekins. Using a knife or icing spatula, smooth down the surface. Run a knife, icing spatula, or your thumb around the rim at the top, creating a “channel” between the batter and the rim of your pan. Feel free to wipe the edges clean with a towel, though I don’t always do that and don’t notice a difference in appearance or rise.", <br />, <u>9.Bake:</u>, "Place baking sheet with ramekins on top in the oven. Immediately reduce oven temperature to 375°F (191°C). Bake for 13-14 minutes or until the edges are set and the center just barely jiggles when you give the pan a light tap. Avoid opening/closing the oven too much.", <br />, "10.Remove from the oven and serve immediately plain or with optional toppings. Soufflés begin to fall within minutes. You’ll still have that sponge-like texture underneath a crackly top, though it settles into a denser texture as time passes. Cover and store leftovers in the refrigerator for up to 3 days."],
      preptime: "30 minutes",
      cooktime: "14 minutes",
      totaltime: "45 minutes",
      servings: "four 6 ounce soufflés (6 Servings)",
      calories: "255 kcal per serving",
    },
    {
      title: "Japanese Sushi",
      image: "/images/recipes/15.jpg",
      authorImg: "/images/topchefs/img_5.jpg",
      desc: "Sushi is a Japanese dish of prepared vinegared rice, usually with some sugar and salt, accompanied by a variety of ingredients, such as seafood—often raw—and vegetables.",
      authorName: "Joe Goldberg",
      ingredients: [<u>For Sushi Rice:</u>, <br />, "3 rice cooker cups uncooked Japanese short-grain rice (3 rice cooker cups (180 ml x 3 = 540 ml) yields roughly 5-6 servings (5 ¼ US cups or 990 g); you must use short-grain Japanese rice to make sushi; otherwise, rice will fall apart.)", <br />, "540 ml water", <br />, "1 piece kombu (dried kelp) (5 g; 2 inches x 2 inches or 5 cm x 5 cm; optional but it gives a nice aroma!)", "⅓ cup rice vinegar (unseasoned) (you can substitute it with bottled sushi vinegar (seasoned rice vinegar))", "3 Tbsp sugar (skip if you are using bottled sushi vinegar)", <br />, "1 ½ tsp kosher salt (Diamond Crystal; use half for table salt) (skip if you are using bottled sushi vinegar)", <br />, <u>For the Fillings:</u>, <br />, "1 Japanese or Persian cucumber (yield 8 rolls)", <br />, "7 oz sashimi-grade tuna (yield 12 rolls)", <br />, "1 box natto (fermented soybean) (yield 2 rolls)", <br />, "For Tezu (Finger Dipping Water)", <br />, "¼ cup water", <br />, "2 tsp rice vinegar (unseasoned)", <br />, <u>Everything Else:</u>, <br />, "5 sheets nori (dried laver seaweed)", <br />, "soy sauce", <br />, "wasabi (optional)", <br />, "sushi ginger (gari)"],
      directions: [<u>To Prepare Sushi Rice:</u>, <br />, "1.For this recipe, 3 rice-cooker-cups of uncooked rice will yield 5 ¼ US cups and can make 10 Hosomaki (thin sushi rolls).", <br />, "2.Cook Japanese white rice is mixed with a special sushi rice vinegar.. Cover the sushi rice and the completed rolls with a damp cloth/plastic wrap at all times to prevent from drying.", <br />, <u>To Prepare the Fillings:</u>, <br />, "1.Cut both ends of the cucumber. Then cut in half lengthwise and cut again in half so you now have 4 strips. Remove the seeds with knife and cut in half lengthwise again. You should end up with 8 cucumber strips.", <br />, "2.Cut the tuna into ¼- ½” slices and then cut into ¼- ½” thick long strips.", <br />, "3.Take out the natto from the container and season with soy sauce or seasoning that came with the package. Mix everything up until it’s slimy and bubbly.", <br />, <u>To Roll Sushi:</u>, <br />, "1.Make vinegared finger-dipping water (Tezu) by combining water and rice vinegar in a small bowl. Applying this water to your hands prevents rice from sticking to your hands.", <br />, "2.Cut nori in half. Even though it may look it, Nori sheets are not perfect square; therefore cut the longer side of rectangular in half. Also, nori gets stale easily, so store unused nori in an air-tight bag and take out only as much as you need.", <br />, "3.Place the sushi mat on a working surface. The bamboo strings should go sideways so you can roll them up. And put the nori half sheet on the bamboo mat, with one of nori’s long side close to the back edge of the mat. Leave about 3-4 slats visible on the side nearest to you. The shiny side of nori should face DOWN.", <br />, "4.Moisten your hand before you touch sushi rice.", <br />, "5.Using a ½-cup measuring cup, measure ½ cup (90 g) of sushi rice into your hand. This way the amount of rice for each roll is the same and the rolls will be equal size. Make sure to wet the measuring cup so the rice won't stick. I know, this is not a “proper” way, but until you can grab a perfect amount of rice each time, this trick will do!", <br />, "6.Place the sushi rice on the left center of nori. Now spread the rice across the nori, leaving a 1” space along the top edge of the nori. Use your right hand to spread the rice toward the right and use your left fingers to keep the rice away from the 1” space on the top of the nori.", <br />, "7.Spread the rice evenly with both fingers, still keeping the 1” space on the top. Wet your fingers in dipping water if rice starts to stick to your fingers.", <br />, "8.Place the filling (tuna, cucumber, natto) at the middle of rice. If your tuna or cucumber is a bit too short, add extra pieces on the end. Hold the filling down using your fingers.", <br />, "9.With one swift movement, roll the sushi over the filling and land right where the edge of the rice is (see you still see the 1”nori space after rolling).", <br />, "10.Don’t move the sushi mat yet and gently shape and tighten the roll with your fingers from outside of the mat. Shape the sushi roll into square (or round). Then finally lift the sushi mat and rotate the roll once to seal the edge of nori. Again gently squeeze and tighten the roll with your fingers.", <br />, "11.To cut a sushi roll, wet your knife with a damp towel and cut the roll in half first. You should “push then pull” the knife while cutting through the sushi. Wet the knife again and cut each half roll into 3 pieces. Serve with soy sauce, wasabi, and pickled ginger.", <br />, <u>To Store:</u>, <br />, "1.Sushi rolls should be consumed right away, but they can be stored in the refrigerator for up to 24 hours. I highly recommend keeping them in an airtight container or a plate wrapped tightly with plastic and then wrap around the container/plate with a thick kitchen towel so the food stay safe in a cool environment but rice doesn't get hard from cold air in the refrigerator."],
      preptime: "60 minutes",
      cooktime: "20 minutes",
      totaltime: "80 minures",
      servings: "10 Sushi Rolls",
      calories: "205 kcal per Roll",
    },
    {
      title: "Chicken Pan Pizza",
      image: "/images/recipes/16.jpg",
      authorImg: "/images/topchefs/img_6.jpg",
      desc: "Pan pizza is a pizza baked in a deep dish pan or sheet pan. Italian tomato pie, Sicilian pizza, Chicago-style pizza and Detroit-style pizza may be considered forms of pan pizza.",
      authorName: "Daisy Edgar-Jones",
      ingredients: ["4 boneless skinless chicken breasts", <br />, "Kosher salt and freshly ground black pepper, to taste", <br />, "2 tablespoons olive oil", <br />, "3 cloves garlic, minced", <br />, "1 28-ounce can crushed tomatoes", <br />, "1 teaspoon dried basil", <br />, "½ teaspoon dried oregano", <br />, "½ teaspoon dried parsley", <br />, "½ teaspoon crushed red pepper flakes, optional", <br />, "1 cup shredded mozzarella cheese", <br />, "¼ cup mini pepperoni", <br />, "¼ cup basil leaves"],
      directions: ["1.Preheat oven to broil.", <br />, "2.Season chicken with salt and pepper, to taste.", <br />, "3.Heat olive oil in a large skillet over medium heat. Add chicken and cook, flipping once, until cooked through, about 4-5 minutes on each side; set aside.", <br />, "4.Add garlic to the skillet, and cook, stirring frequently, until fragrant, about 1-2 minutes.", <br />, "5.Stir in crushed tomatoes, basil, oregano, parsley and red pepper flakes; season with salt and pepper, to taste.", <br />, "6.Bring to a boil; reduce heat to low and simmer, stirring occasionally, until sauce has thickened, about 15-20 minutes.", <br />, "7.Return chicken to the skillet. Top with mozzarella and mini pepperonis.", <br />, "8.Place into oven and cook until melted and golden brown, about 2 minutes.", <br />, "9.Serve immediately, garnished with basil, if desired."],
      preptime: "15 minutes",
      cooktime: "30 minutes",
      totaltime: "45 minutes",
      servings: "4",
      calories: "457 kcal per serving",
    },
    {
      title: "Spanish Tortilla",
      image: "/images/recipes/17.jpg",
      authorImg: "/images/topchefs/img_1.jpg",
      desc: "Spanish omelette or Spanish tortilla is a traditional dish from Spain. Celebrated as a national dish by Spaniards, it is an essential part of the Spanish cuisine.",
      authorName: "Fivel Stewart",
      ingredients: ["2 lbs potatoes Yukon Golds work well (1kg)", <br />, "Salt to taste", <br />, "8 large eggs free range if possible", <br />, "1 large onion", <br />, "Extra Virgin Olive Oil enough to fry the potatoes and cook the tortilla. You can substitute a neutral oil for frying if you wish (but good quality olive oil really makes a difference!)."],
      directions: ["1.Peel the potatoes and rinse them under cold water.", <br />, "2.Slice the potatoes into thin slices, I prefer about 1/2 centimeter (some prefer thicker). I use a mandolin to do this quickly and easily.", <br />, "3.Pat the potato slices dry and put them into a large bowl, sprinkle with salt, and mix well.", <br />, "4.Heat a 1/2 inch of high quality extra virgin olive oil in a large frying pan at medium low heat.", <br />, "5.When the oil is hot, add the potatoes and add more oil if necessary until all are covered.", <br />, "6.Cook the potatoes for 20 minutes at a low heat (they may break apart, that is okay).", <br />, "7.While the potatoes are cooking, beat the eggs in a large bowl and season with some salt.", <br />, "8.Slice the onion as thin as possible (julienne style) and fry over a low heat in a separate heavy pan (I like stainless steel) for about 10-20 minutes until they begin to caramelize (stir often).", <br />, "9.When the onions are caramelized, drain off any excess oil and add to the egg mixture.", <br />, "10.When the potatoes have been frying 20 minutes, remove them with a slotted spoon into a strainer and allow to cool off while any excess oil drips away.", <br />, "11.After a few minutes, add the potatoes to the egg mixture and stir well.", <br />, "12.Let the egg mixture sit for about 20 minutes.", <br />, "13.In the same pan where you fried the potatoes, remove all the oil (you can reuse it!) and over a medium low heat add the egg mixture.", <br />, "14.Over medium-low heat, cook the tortilla for about 6-8 minutes per side. Make sure the heat is low enough or the tortilla will cook too quickly and be rubbery. You can run a rubber spatula along the edges to make sure the tortilla isn't sticking.", <br />, "15.When you are sure that the bottom is cooked and you want to flip the tortilla, take a large plate and put it over the pan and flip quickly! Some egg will likely slip out– it’ll be messy– but that’s okay!", <br />, "16.Finally, slide out of the pan onto a serving plate and let cool a little before diving in."],
      preptime: "60 minutes",
      cooktime: "15 minutes",
      totaltime: "85 minutes",
      servings: "8 slices",
      calories: "215.41 kcal",
    },
    {
      title: "Pancakes",
      image: "/images/recipes/18.jpg",
      authorImg: "/images/topchefs/img_2.jpg",
      desc: "A pancake is a flat cake, often thin and round, prepared from a starch-based batter that may contain eggs, milk and butter and cooked on a hot surface such as a griddle or frying pan, with oil or butter.",
      authorName: "Patrick Bateman",
      ingredients: ["1 ½ cups all-purpose flour", <br />, "3 ½ teaspoons baking powder", <br />, "1 tablespoon white sugar", <br />, "¼ teaspoon salt, or more to taste", <br />, "1 ¼ cups milk", <br />, "3 tablespoons butter, melted", <br />, "1 egg", <br />, <u>TOPPINGS:</u>, <br />, "Bananas, blueberries, mapple syrup, peanut butter, chocolate chips and whipped cream e.t.c."],
      directions: [<u>MAKE BATTER:</u>, <br />, "1.Whisk flour, sugar, baking powder, and the salt in a medium bowl.", <br />, "2.Warm milk in the microwave or on top of the stove until lukewarm, not hot. You should be able to keep your finger submerged for 10 seconds.", <br />, "3.Whisk milk, egg, melted butter, and vanilla extract until combined. (By warming the milk slightly, the melted butter mixes into the milk instead of turning into small lumps).", <br />, <u>COOK PANCAKES:</u>, <br />, "1.Heat a large skillet (or use griddle) over medium heat. The pan is ready if when you splatter a little water onto the pan surface, the water dances around the pan and eventually evaporates.", <br />, "2.Make a well in the center of the flour mixture, pour milk mixture into the well and use a fork to stir until you no longer see clumps of flour. It is okay if the batter has small lumps – it is important not to over-mix the batter.", <br />, "3.Lightly brush skillet with melted butter (this is optional if you have a high-quality non-stick pan). Use a 1/4-cup measuring cup to spoon batter onto the skillet. Gently spread the batter into a 4-inch circle.", <br />, "4.When edges look dry, and bubbles start to appear and pop on the top surfaces of the pancake, turn over. This takes about 2 minutes. Once flipped, cook another 1 to 2 minutes or until lightly browned and cooked in the middle. Serve immediately with warm syrup, butter, and berries."],
      preptime: "5 minutes",
      cooktime: "15 minutes",
      totaltime: "20 minutes",
      servings: "Makes 4 servings, 2 pancakes each",
      calories: "158 kcal per serving",
    },
    {
      title: "Napoletana Pizza",
      image: "/images/recipes/19.jpg",
      authorImg: "/images/topchefs/img_3.jpg",
      desc: "Neapolitan pizza, also known as Naples-style pizza, is a style of pizza made with tomatoes and mozzarella cheese.",
      authorName: "Mathew Murdock",
      ingredients: ["1 ball Best Homemade Pizza Dough", <br />, "⅓ cup Easy Pizza Sauce", <br />, "3 ounces fresh mozzarella cheese (or about ¾ cup shredded mozzarella)", <br />, "Kosher salt", <br />, "2 basil leaves", <br />, "Semolina flour or cornmeal, for dusting the pizza peel"],
      directions: ["1.Prepare the dough for Pizza.", <br />, "2.Place a pizza stone in the oven and preheat to 500°F. OR preheat your pizza oven (here’s the pizza oven we have!).", <br />, "3.Make the Homemade Pizza Sauce.", <br />, "4.Slice the mozzarella into ¼ inch thick pieces. If it’s incredibly watery fresh mozzarella (all brands vary), you may want to let it sit on a paper towel to remove moisture for about 15 minutes then dab the mozzarella with the paper towel to remove any additional moisture.", <br />, "5.When the oven is ready, stretch the dough into a circle; see How to Stretch Pizza Dough for instructions. Sprinkle a pizza peel with semolina flour or cornmeal, then carefully place the dough on top. Spread the pizza sauce across the dough. Top with mozzarella cheese.  Taste a bite of the mozzarella cheese; if it does not taste salty, add a few pinches of kosher salt to the pizza.", <br />, "6.If you’re baking in a pizza oven, add the basil leaves. For baking in a standard oven, add the basil leaves after you bake (the leaves turn black in a standard oven).", <br />, "7.Transfer the pizza to the pizza stone on the pizza peel, then bake until the cheese is melted, about 7 minutes in the oven (or 1 minute in the pizza oven). Slice into pieces and serve immediately."],
      preptime: "60 minutes",
      cooktime: "10 minutes",
      totaltime: "70 minutes",
      servings: "6 slices, 6 servings",
      calories: "165 cal, serving size:slice",
    },
    {
      title: "Dal Makhni",
      image: "/images/recipes/20.jpg",
      authorImg: "/images/topchefs/img_4.jpg",
      desc: "Dal makhani is a dish originating in Punjab, India. A relatively modern variation of traditional lentil dishes, it is made with urad dal and other pulses, and includes butter and cream.",
      authorName: "Keira Knightley",
      ingredients: [<u>MAIN INGREDIENTS:</u>, <br />, "¾ cup whole urad dal , 140 grams (whole black gram)", <br />, "¼ cup rajma , 40 grams (kidney beans)", <br />, "3 cups water for pressure cooking , 750 ml water", <br />, "½ cup finely chopped onions , 50 grams onion or 1 medium sized onion", <br />, "1 teaspoon chopped green chilies or serrano peppers or 1 to 2 green chillies", <br />, "2 teaspoons Ginger Garlic Paste or 6 to 7 small to medium-sized garlic + 1 inch ginger – crushed to a paste in mortar-pestle", <br />, "2 large tomatoes , 200 grams tomatoes – pureed or 1 cup tomato puree", <br />, "½ teaspoon cumin seeds", <br />, "2 to 3 cloves", <br />, "2 to 3 green cardamoms", <br />, "1 black cardamom", <br />, "1 inch cinnamon", <br />, "1 small to medium tej patta (Indian bay leaf)", <br />, "½ teaspoon red chili powder or cayenne pepper or smoked paprika", <br />, "2 to 3 pinches grated nutmeg or ground nutmeg powder", <br />, "1 cup water or add as required", <br />, "¼ to ⅓ cup low fat cream or half and half or 2 tablespoons heavy cream or", <br />, "¼ teaspoon crushed kasuri methi (dry fenugreek leaves) – optional", <br />, "3 tablespoon Butter – salted or unsalted", <br />, "salt as required", <br />, <u>FOR GARNISH:</u>, <br />, "1 to 2 tablespoons chopped coriander leaves (cilantro)", <br />, "½ tablespoon low fat cream or half and half for garnish – optional", <br />, "1 inch ginger julienne – optional"],
      directions: [<u>PREPARATION:</u>, <br />, "1.Soak both the whole urad dal and rajma overnight in enough water for 8 to 9 hours or overnight. Later drain them well.", <br />, "2.Rinse both the lentils a couple of times in water.", <br />, "3.Drain again and then add them in a 3 litre pressure cooker. Add water and stir well.", <br />, "4.Pressure cook for 18 to 20 whistles on a high flame, till both the urad dal and rajma have cooked thoroughly and softened. If they are not cooked, then add about ½ cup water again and pressure cook for 4 to 5 whistles more.", <br />, "5.The urad dal should melt in the mouth and should not give any bite or resistance when eaten. You can also just mash the urad dal with a spoon or with your fingers to check the doneness. The same rule applies for rajma too. Keep the cooked beans aside.", <br />, "6.In a blender or mixer jar, take chopped tomatoes and blend to a smooth puree. Set aside.", <br />, "7.You can also add ready 1 cup tomato puree instead of blending the tomatoes. No need to blanch the tomatoes while pureeing.", <br />, <u>MAKING DAL MAKHNI:</u>, <br />, "1.In a pan, now heat butter. You can use salted butter or unsalted butter.", <br />, "2.Add the whole spices – cumin seeds, cloves, green cardamoms, black cardamom, 1 inch cinnamon, 1 small to medium tej patta.", <br />, "3.Fry for some seconds till the spices sputter and become aromatic.", <br />, "4.Add finely chopped onions.", <br />, "5.Stir and sauté the onions on a low or medium-low heat often till they become light golden.", <br />, "6.Add the ginger garlic paste. Stir again and sauté for some seconds till the raw aroma of ginger-garlic goes away.", <br />, "7.Add the chopped green chilies and sauté for a minute.", <br />, "8.Add the prepared tomato puree and mix well.", <br />, "9.Add red chili powder and 2 to 3 pinches of grated nutmeg or nutmeg powder.", <br />, "10.Stir very well and sauté this mixture on a low to medium flame, till you see fat releasing from the sides.", <br />, "11.Then add the cooked urad dal and rajma beans along with the stock. Also add 1 cup water or as required.", <br />, <u>SLOW COOKING:</u>, <br />, "1.Stir very well and simmer the dal makhani uncovered on a low flame.", <br />, "2.Keep on stirring often, so that the lentils don’t stuck to the bottom of the pan.", <br />, "3.Once it has begun to thicken, add salt as required.", <br />, "4.Stir very well and continue to simmer on a low flame. Keep on stirring when the lentils are simmered on low heat.", <br />, "5.When simmering you can add more water if the gravy looks thick or dry. The longer you keep dal makhani to simmer, the better it tastes.", <br />, "6.I kept it for about an overall 25 minutes on a low flame. Do keep on stirring at intervals.", <br />, "7.When the gravy has thickened enough, then add cream. Dal makhani is not too thick or too thin. It has a medium consistency.", <br />, "8.Mix the cream very well. Then switch off the heat.", <br />, "9.Add crushed kasuri methi (dried fenugreek leaves). Mix again.", <br />, "10.Cover and set dal makhani aside, if you are proceeding to the dhungar method. Or else you can serve dal makhni straight away."],
      preptime: "4 hours",
      cooktime: "1 hour",
      totaltime: "5 hours",
      servings: "4",
      calories: "308 kcal per serving",
    },
    {
      title: "Risotto",
      image: "/images/recipes/21.jpg",
      authorImg: "/images/topchefs/img_5.jpg",
      desc: "Risotto is a northern Italian rice dish cooked with broth until it reaches a creamy consistency. The broth can be derived from meat, fish, or vegetables.",
      authorName: "Joe Goldberg",
      ingredients: "",
      directions: "",
      preptime: "",
      cooktime: "",
      totaltime: "",
      servings: "",
      calories: "",
    },
    {
      title: "Salade Niçoise",
      image: "/images/recipes/22.jpeg",
      authorImg: "/images/topchefs/img_6.jpg",
      desc: "Salade niçoise, salada nissarda in the Niçard dialect of the Occitan language, insalata nizzarda in Italian, is a salad that originated in the French city of Nice.",
      authorName: "Daisy Edgar-Jones",
      ingredients: "",
      directions: "",
      preptime: "",
      cooktime: "",
      totaltime: "",
      servings: "",
      calories: "",
    },
  ].sort(() => Math.random() - 0.5);

  return (
    <div>
      <PreviousSearches />
      <div className="recipes-container">
        {/* <RecipeCard /> */}
        {recipes.map((recipe, index) => (
          <RecipeCard key={index} recipe={recipe} />
        ))}
      </div>
    </div>
  );
}
